matrix:
  include:
    - language: go
      go:
        - 1.15
      install:
        - pushd /home/travis
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
        - unzip protoc-3.13.0-linux-x86_64.zip
        - go get google.golang.org/grpc github.com/golang/protobuf/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
        - export PATH=$PWD/bin:$PATH
        - popd
      before_script:
        - ln -sf ${TRAVIS_BUILD_DIR} ${GOPATH}/src/pitwall
        - bash backend/prepare_protos.sh
      script:
        - go build -v ./...
        - go test -v ./...

    - language: node_js
      node_js:
        - node
      install:
        - pushd /home/travis
        - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
        - unzip protoc-3.13.0-linux-x86_64.zip
        - wget https://github.com/grpc/grpc-web/releases/download/1.2.1/protoc-gen-grpc-web-1.2.1-linux-x86_64
        - mv protoc-gen-grpc-web-1.2.1-linux-x86_64 bin/protoc-gen-grpc-web
        - chmod +x bin/protoc-gen-grpc-web
        - export PATH=$PWD/bin:$PATH
        - popd
      before_script:
        - protoc ./protos/*.proto --js_out=import_style=commonjs:frontend/src/
        - protoc ./protos/service.proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:frontend/src
        - cd frontend
        - npm install
      script:
        - npm run build
